# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73dedbff8a8d975699460b220d62a93df40a33326702c0d0b1ade88417c01bd088b221d0d351d1c97a44a190c1b5dab00a8469fd03c403f0e96658cd4d824271

test:
  secret_key_base: 166eb3aa05486ff2f9e8d5e4411053952eb0e0a145f592a29dbdaea71078eeb8f5e022aabfc879243e8e658a418fad913ce032202139bd9f476afb8c46d83346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
